### ISSUE TITLE
Only use DEBUG_BACKTRACE_IGNORE_ARGS for PHP_VERSION >= 5.3.6

### ISSUE THREAD

**Issue by RichieB2B** [kamisama/Cake-Resque#80]
When I enable debug (using PHP 5.3.3 on CentOS) I get: 
```
Use of undefined constant DEBUG_BACKTRACE_IGNORE_ARGS - assumed 'DEBUG_BACKTRACE_IGNORE_ARGS' [APP/Plugin/CakeResque/Lib/CakeResque.php, line 144]
```
I believe this flag was introduced in PHP 5.3.6, so please only use it when appropriate.

**Comment by kamisama** [comment]
Fixed in 4.1.1

**Comment by RichieB2B** [comment]
Thanks for the fix but you missed two more instances of this bug on lines 189 and 232.
